### ISSUE TITLE
Add support for multiple stories/servers at once

### ISSUE THREAD

**Issue by 2br-2b** [2br-2b/StoryBot#10]

**Comment by 2br-2b** [comment]
Fixing #3 will help with this

**Comment by archfan7411** [comment]
What would the preferred behavior be if it's one person's turn on two stories at once?

**Comment by 2br-2b** [comment]
I was trying to think about this. In this case:
1. The user must specify which bot they're responding to;
2. The user has to respond to the bots in the order he was chosen;
3. The user has to respond to the bots in the order of how much time is left for each;
4. The user won't get chosen for a story if they have another story pending.

It seems to me that, unless implemented well, 1 could end up being confusing for users.

2 is my second-favorite option.

3 could cause confusion. For example, say you're on a server with a 3-day time limit. You spend a day coming up with your story piece. Before you can submit it tho, you're chosen for a one-day story and are forced to respond. Then, the 3-day people have to wait needlessly for the person to write another story.

I like 4 best, but this could lead to situations where there are no available authors for a story.


I like 4 best, but 2 may be easier to implement.

**Comment by archfan7411** [comment]
> It seems to me that, unless implemented well, 1 could end up being confusing for users.

Indeed, the only way I can think of would be "reply to the story you're adding to"

I think that 2 and 3 would still be very confusing for users. 4 would solve it, but like you said, could very easily end up in gridlock, especially if you have a small group of people doing several stories together. 

Overall I think 1 is best, if implemented well.

**Comment by 2br-2b** [comment]
Discord bots are able to add buttons to messages like so:
![image](https://user-images.githubusercontent.com/43968991/198838628-f7a7f5af-1bf3-42dd-a97b-8b2b10ab069f.png)
This could be a good way to select a story for option 1. The message body would contain the current story being edited as well as the icon for the server, and the buttons would let you choose a story.

For option 2, I was thinking it would ping you saying "You have one other story in your queue: servername. Finish your current story to work on the new one" or something like that, but that could also be confusing.

I don't have strong opinions on this, except that 3 would probably be a bad idea

**Comment by 2br-2b** [comment]
I asked a friend/user from two different stories and he said option 4 would be prefered

**Comment by 2br-2b** [comment]
I think that 1 is the best option, so let's examine some implementations.

1.1) Using the [aforementioned button scheme](https://github.com/2br-2b/StoryBot/issues/10#issuecomment-1295864117), the user should be able to select which server their DM is currently "focused in". Then, whenever the user runs a command in a DM, the bot will determine which server the DM is "focused in" and respond accordingly. For example, if I run `/turn` in a DM while I'm an author in two servers, it'll detect the "focused" server and respond based on the server.

In addition, the bot will only add onto the story if it is the current user's turn in the "focused" server of a DM. If it seems that a user was trying to add to the story when they're "focused" on a server where it's not their turn, the bot can notify them (and potentially give them a button to move the addition to another "focus").

The problem this leaves is if a user accidentally is focused on the wrong server it's their turn on. This will cause the story chunk to successfully be added to the wrong story.

1.2) When a user from multiple servers adds to a story, they'll get a confirmation message (with buttons) of "Which story is this a part of?" along with a cancel button. That way, it'll confirm that the right story chunks get added to the right server. This would probably happen whenever a user is in multiple servers, even if it's not their turn in one or more. Any servers it is the user's turn on will show up; the cancel button will be there in case they missed something saying they were skipped.


I think I like 1.2 better, but am very open to feedback.

We could also do an initial implementation assuming that a user is only an author in one server until a decision is made about this.

**Comment by 2br-2b** [comment]
Implemented by #37
