### ISSUE TITLE
Remove hardcoded id numbers

### ISSUE THREAD

**Issue by 2br-2b** [2br-2b/StoryBot#3]

**Comment by JosiahWI** [comment]
Can we save this state in a simple .txt file?

**Comment by 2br-2b** [comment]
I was thinking either a .txt or a .json file. A json file may be easier to dump/load

**Comment by JosiahWI** [comment]
It would be nice to be able to register ourselves automatically and have our user ID be saved by the bot.

**Comment by 2br-2b** [comment]
That functionality is included already - https://github.com/2br-2b/StoryBot/blob/5a3bc188f630978e03881e7cc6317c1ec7dc69b9/dmlistener.py#L219-L229

This is specifically referring to cases like https://github.com/2br-2b/StoryBot/blob/5a3bc188f630978e03881e7cc6317c1ec7dc69b9/dmlistener.py#L56 and https://github.com/2br-2b/StoryBot/blob/5a3bc188f630978e03881e7cc6317c1ec7dc69b9/dmlistener.py#L106

**Comment by archfan7411** [comment]
I agree #10 is inherently tied to this, and I think that a solution for this should be prepared with the expectation of multiple servers/stories being enacted sometime in the future.

> It would be nice to be able to register ourselves automatically and have our user ID be saved by the bot.

Allowing anyone to add themselves via command could cause confusion and delay IMO, given the ease of story sabotage, and the fact that the story usually works best when being written by a small group of people.

I suggest that we introduce the concept of a bot "admin" (being 2br-2b in this context) who can add users to the story using a command. #10 could then extend this to have server- or story-specific "admins".

**Comment by 2br-2b** [comment]
This specific issue is fixed with 3b716117d5dc51a3c6d3cc0810ff4cbcbabca52e.

Regarding permissions, you're right, maybe adding people (not removing yourself) should be an admin-only command to prevent malicious actors. On the other hand, it's nice to be able to just leave the bot running as an admin. For example, if someone needs to sign off for a bit, they may want to be removed, then re-added later. It'd be nice if admin rights weren't needed for this. Maybe there should be an option to make adding a user require admin rights?

I updated the bot to have a list of overall admins, though.
