### ISSUE TITLE
Have the bot create all the needed files on first run

### ISSUE THREAD

**Issue by 2br-2b** [2br-2b/StoryBot#4]

**Comment by 2br-2b** [comment]
Right now, a blank story.txt and a user.txt file with a random user in it

**Comment by JosiahWI** [comment]
Why a random user?

**Comment by 2br-2b** [comment]
It needs to have some user in the user.txt file when it's initialized.

Either way, fixed with 24b9b43addb2f88b0b484a8658036b93a6f42965
