### ISSUE TITLE
Automatically add line breaks to make the story readable in Discord

### ISSUE THREAD

**Issue by 2br-2b** [2br-2b/StoryBot#7]
![image](https://user-images.githubusercontent.com/43968991/197901317-50fc0525-3806-4a70-98f8-6ca5c9b3fa1d.png)

**Comment by 2br-2b** [comment]
Note: .txt embeds don't display in the same way on mobile as they do on desktop:
![signal-2022-10-25-194513](https://user-images.githubusercontent.com/43968991/197902377-f52511e8-7f81-4698-8c00-29efbe19f017.jpeg)
This feature will only effect desktop clients.


We need to determine an optimal line length. This is a screenshot when I have the Discord window as thin as Windows lets me make it:
![image](https://user-images.githubusercontent.com/43968991/197902479-7a1a8fd9-fb2d-4d86-97d9-0e467b48c62a.png)


We need to figure out how long of a line we want to show (if we want to cut it down).

**Comment by JosiahWI** [comment]
Does this involve adding line breaks to the text file, or can we add them to the embed/preview only? One of the use-cases for downloading the text file is to copy the text into a word processor for more powerful editing, where having line breaks in the wrong places would generate a lot of work for the editors to remove them all again.

**Comment by 2br-2b** [comment]
You're right - adding line breaks would probably be best just in the returned text file. Discord seems to handle line breaks in messages fine, and it'd be good to preserve the original story without line breaks.

**Comment by 2br-2b** [comment]
To make the story more readable, as pointed out by a friend in Discord, could we make the story scrollable thru buttons on a message?

**Comment by 2br-2b** [comment]
Given #11 and 2faf24ffb5f1c756223e86cf1aeb7e04cfda2dc0, this is probably a low-priority issue now. Does this still need to be implemented?

**Comment by 2br-2b** [comment]
I'll close the issue, as the  underlying problem seems to be fixed for now. We can reopen this or convert it to a discussion if we want to continue working on it.
