### ISSUE TITLE
Add support for ending lines with `...`

### ISSUE THREAD

**Issue by 2br-2b** [2br-2b/StoryBot#8]
Sometimes people end their stories with a `...`. If this happens:
1. The ellipses should be removed;
2. The story should not add a period to the end of the story segment;
3. Maybe the bot should notify the next user that they'll be continuing the last sentence?

**Comment by archfan7411** [comment]
Ellipses aren't always used to signify the need for continuation, are they? Sometimes they're just there for dramatic effect.

**Comment by JosiahWI** [comment]
Because there's always an empty space added at the end, it's also not possible for the next user to put it back in.
