### ISSUE TITLE
De-spaghetti-ify the code

### ISSUE THREAD

**Issue by 2br-2b** [2br-2b/StoryBot#9]
There are lots of places in the code where the same is rewritten multiple times. The code needs to be fixed up and made neater.

**Comment by 2br-2b** [comment]
There should at least be methods for:
- [ ] `get_user`, then `fetch_user`
- [ ] Send a dm
- [ ] Choosing a new user

**Comment by JosiahWI** [comment]
Are you thinking mostly of extracting methods, or are there other types of refactoring that should be done as well?

**Comment by 2br-2b** [comment]
Mostly extracting methods, but other refactoring isn't out of the question (I wrote this code 4 years ago, so it's quite messy).
